[programs.localnet]
faucet = "JDnDwBLCw8nnvbrhqT2eyngWGqAapRxBuJcCmMYTbbE2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/zhuangsirui/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
